import { fileSetup } from "./file/mod.ts";
import { userSetup } from "./user/mod.ts";
import { tagSetup } from "./tag/mod.ts";
import { categorySetup } from "./category/mod.ts";
import { courseSetup } from "./course/mod.ts";
import { articleSetup } from "./article/mod.ts";
import { walletSetup } from "./wallet/mod.ts";
import { paymentSetup } from "./payment/mod.ts";
import { couponSetup } from "./coupon/mod.ts";
import { productSetup } from "./product/mod.ts";
import { scoringSetup } from "./scoring/mod.ts";
import { referralSetup } from "./referral/mod.ts";
import { bookingSetup } from "./booking/mod.ts";
import { analyticsSetup } from "./analytics/mod.ts";
import { downloadSetup } from "./download/mod.ts";
import { adminSetup } from "./admin/mod.ts";
// import { testSetup } from "./test/mod.ts"; // Disabled - directory renamed to test.disabled
import { enrollmentSetup } from "./enrollment/mod.ts";
import { smsSetup } from "./sms/mod.ts";
import { emailSetup } from "./email/mod.ts";
import { searchSetup } from "./search/mod.ts";
import { certificateSetup } from "./certificate/mod.ts";
import { invoiceSetup } from "./invoice/setup.ts";
import { groupSetup } from "./group/setup.ts";

export const functionsSetup = () => {
  fileSetup();
  userSetup();
  tagSetup();
  categorySetup();
  courseSetup();
  articleSetup();
  walletSetup();
  paymentSetup();
  couponSetup();
  productSetup();
  scoringSetup();
  referralSetup();
  bookingSetup();
  enrollmentSetup();
  groupSetup();
  analyticsSetup();
  downloadSetup();
  adminSetup();
  smsSetup();
  emailSetup();
  searchSetup();
  certificateSetup();
  invoiceSetup();
  directApiSetup();
  // testSetup(); // Disabled - test module renamed to test.disabled
};
import { directApiSetup } from "./alternative/directApi/mod.ts";
