import { MetadataRoute } from 'next';

export default function robots(): MetadataRoute.Robots {
  const baseUrl = process.env.NEXT_PUBLIC_BASE_URL || 'https://irac.ir';

  return {
    rules: [
      {
        userAgent: '*',
        allow: [
          '/',
          '/en/',
          '/fa/',
          '/courses/',
          '/articles/',
          '/workshops/',
          '/about/',
          '/contact/',
          '/gallery/',
          '/services/',
          '/coworking/',
          '/events/',
          '/search/',
          '/privacy-policy/',
          '/terms-of-service/',
          '/faq/',
        ],
        disallow: [
          '/admin/',
          '/api/',
          '/dashboard/',
          '/profile/',
          '/cart/',
          '/checkout/',
          '/payment/',
          '/auth/',
          '/login/',
          '/register/',
          '/reset-password/',
          '/verify/',
          '/wallet/',
          '/orders/',
          '/invoices/',
          '/certificates/',
          '/_next/',
          '/static/',
          '/temp/',
          '/backup/',
          '/logs/',
          '*.json$',
          '*.xml$',
          '/search?*',
          '/filter?*',
          '*?page=',
          '*?sort=',
          '*?filter=',
          '*utm_*',
          '*ref=*',
          '*fbclid=*',
          '*gclid=*',
        ],
        crawlDelay: 1,
      },
      {
        userAgent: 'Googlebot',
        allow: [
          '/',
          '/en/',
          '/fa/',
          '/courses/',
          '/articles/',
          '/workshops/',
          '/about/',
          '/contact/',
          '/gallery/',
          '/services/',
          '/coworking/',
          '/events/',
          '/search/',
          '/privacy-policy/',
          '/terms-of-service/',
          '/faq/',
        ],
        disallow: [
          '/admin/',
          '/api/',
          '/dashboard/',
          '/profile/',
          '/cart/',
          '/checkout/',
          '/payment/',
          '/auth/',
          '/login/',
          '/register/',
          '/reset-password/',
          '/verify/',
          '/wallet/',
          '/orders/',
          '/invoices/',
          '/certificates/',
          '/_next/',
          '/static/',
          '/temp/',
          '/backup/',
          '/logs/',
        ],
      },
      {
        userAgent: 'Bingbot',
        allow: [
          '/',
          '/en/',
          '/fa/',
          '/courses/',
          '/articles/',
          '/workshops/',
          '/about/',
          '/contact/',
          '/gallery/',
          '/services/',
          '/coworking/',
          '/events/',
        ],
        disallow: [
          '/admin/',
          '/api/',
          '/dashboard/',
          '/profile/',
          '/cart/',
          '/checkout/',
          '/payment/',
          '/auth/',
          '/_next/',
          '/static/',
        ],
      },
      {
        userAgent: 'facebookexternalhit',
        allow: '/',
      },
      {
        userAgent: 'Twitterbot',
        allow: '/',
      },
      {
        userAgent: 'LinkedInBot',
        allow: '/',
      },
    ],
    sitemap: [
      `${baseUrl}/sitemap.xml`,
      `${baseUrl}/sitemap-0.xml`,
      `${baseUrl}/sitemap-1.xml`,
    ],
    host: baseUrl,
  };
}
